//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poprijunchikAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentType
    {
        public AgentType()
        {
            this.AgentInfo = new HashSet<AgentInfo>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<AgentInfo> AgentInfo { get; set; }
    }
}
