//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poprijunchikAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentInfo
    {
        public AgentInfo()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string AgentName { get; set; }
        public string AgentEmail { get; set; }
        public string Number { get; set; }
        public string LogoPath { get; set; }
        public string AgentAddress { get; set; }
        public int AgentPriority { get; set; }
        public string Director { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        public virtual AgentType AgentType { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
