//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poprijunchikAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> AgentInfoID { get; set; }
        public System.DateTime RealizeDate { get; set; }
        public int ProductCount { get; set; }
    
        public virtual AgentInfo AgentInfo { get; set; }
    }
}
